Document: pyinput
Title: Debian pyinput Manual
Author: <insert document author here>
Abstract: This manual describes what pyinput is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyinput/pyinput.sgml.gz

Format: postscript
Files: /usr/share/doc/pyinput/pyinput.ps.gz

Format: text
Files: /usr/share/doc/pyinput/pyinput.text.gz

Format: HTML
Index: /usr/share/doc/pyinput/html/index.html
Files: /usr/share/doc/pyinput/html/*.html

  
