#!/usr/bin/python
import uinput, udev, time

# Initialize
fd = udev.EvdevStream(udev.FindUinput(), 'w')
fd.write(udev.uinput_user_dev(name="Saitek Magic Bus",
	id=udev.input_id(bustype=0,vendor=0x06A3, product=0x8000, version=0x0111)))
fd.ioctl(uinput.UI_SET_EVBIT, uinput.EV_KEY)
fd.ioctl(uinput.UI_SET_KEYBIT, uinput.KEY_ENTER)
fd.ioctl(uinput.UI_DEV_CREATE)

time.sleep(10)

# Send an event
fd.write(udev.input_event(type=uinput.EV_KEY, code=uinput.KEY_ENTER, value=1))
fd.write(udev.input_event(type=uinput.EV_KEY, code=uinput.KEY_ENTER, value=0))

# Uninit
fd.ioctl(uinput.UI_DEV_DESTROY)
fd.close()

